[package]
name = "tinyrenderer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bresenham = "0.1.1"
image = "0.24.7"
rayon = "1.8.0"
vector3d = "0.2.1"
wavefront = "0.2.3"
